# Generated by Django 5.2.4 on 2025-08-02 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="on_trial",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="paid_until",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
