# Generated by Django 5.2.4 on 2025-08-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_client_on_trial_client_paid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="paid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
